os:
  - linux

language: node_js

node_js: stable

env:
  global:
    - IMAGE=penitence/blog:latest

services:
  - docker

install:
  - yarn install

before_script:
  - git submodule init
  - git submodule update

script:
  - hexo clean
  - hexo generate
  - docker build -t $IMAGE -f Dockerfile .

after_success:
  - docker login -u="$USERNAME" -p="$PASSWORD"
  - docker push $IMAGE

branches:
  only:
    - master